# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
#  schedule:
#    - cron: '0 23 * * *' # JST 8:00
#    - cron: '0 8 * * *'  # JST 17:00
#    - cron: '0 9 * * *'  # JST 18:00
#    - cron: '0 10 * * *' # JST 19:00
#    - cron: '0 11 * * *' # JST 20:00
#    - cron: '0 12 * * *' # JST 21:00

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python
      run: |
        python limit_high.py
    - name: Commit files
      run: |
        git config --global user.email "kabubeikon@gmail.com"
        git config --global user.name "beikon"
        git init
        git add -A
        git commit -m 'Add changes' --allow-empty
      
