name: 決算スケジュール、ストップ高

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
  schedule:
    - cron: '0 12 * * *' # JST 21:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python
      run: |
        python limit_high.py
        python financial_results_schedule.py
    - name: Commit files
      run: |
        git config --global user.email "kabubeikon@gmail.com"
        git config --global user.name "beikon"
        git init
        git add -A
        git commit -m 'Add changes' --allow-empty
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
